# Generated by Django 2.2.6 on 2019-10-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Individual', 'Individual'), ('Institutions', 'Institutions'), ('Companies', 'Companies')], max_length=50)),
            ],
        ),
    ]
